### ISSUE TITLE
Todo: Track contributors

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#1]
Allow external contributors for different objects in the DB

 -  [ ] Create contributors group. Assign trusted users to this group
 - [ ] Trusted users see buttons when they log in allowing them to contribute stuff
 - [ ] Create contributions model. 
 - [ ] Contributions model stores original model, pk, fieldname, contributor, contribution, approval status, approver, date & time.
 - [ ] Approve script on backend to approve publications
 - [ ] Frontend shows contribution metadata: contributor, approval, dates, etc.

Figure out:
 - Multiple contributions on the same field. Aggregate? Edit?

**Comment by ahankinson** [comment]
Plan of attack is given in #32 . Closing this one in favour of that one.
